import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/index";
import { CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Beltagy Books Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />
        <Header />
        {children}
      </body>
    </html>
  );
}
